### ISSUE TITLE
Link to blog article

### ISSUE THREAD

**Issue by campbell-codes** [RafPe/docker-haproxy-rsyslog#1]
Hi I didn't realise there was a blog article to go with this repo until I stumbled across it later. Any chance it could be included in the readme?

https://rafpe.ninja/2016/05/16/haproxy-logging-within-docker-container/

**Comment by RafPe** [comment]
Hey @andycampbell92 - I just linked it over. Forgot to push out readme file content. Most probably will do that still today! Thanks for pointing it out 👍

**Comment by campbell-codes** [comment]
Thanks, really helpful image! :+1:

**Comment by RafPe** [comment]
Aaaannnnnd its now resolved #2 - still work to be done but at least started!
