### ISSUE TITLE
Container Exited after started with no Error

### ISSUE THREAD

**Issue by hierony94** [RafPe/docker-haproxy-rsyslog#3]
I tried this haproxy-rsyslog (with some modifications), but after I started the container, the container goes to exited state. I started the container using docker-compose (`docker-compose build && docker-compose up -d`). I've checked the docker container logs but I only found this.

> Starting enhanced syslogd: rsyslogd.
[WARNING] 288/041007 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:28] : 'maxconn' ignored because backend 'EJ_SERVER_TIER' has no frontend capability. Maybe you want 'fullconn' instead ?

Here My setup :
**docker-compose.yml**
```
haproxy:
  build: .
  container_name: my-running-haproxy
  ports:
    - 443:443
    - 80:9000
    - 514:514/udp  # For Rsyslog

```
**Dockerfile**

```
FROM haproxy:1.7

RUN apt-get update \
    && apt-get install -y rsyslog net-tools \
    && rm -rf /var/lib/apt/lists/*

COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

COPY 49-haproxy.conf /etc/rsyslog.d/49-haproxy.conf
COPY rsyslog.conf /etc/rsyslog.conf

COPY docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
```

**docker-entrypoint.sh**
```
ubuntu@ip-10-0-2-115:~$ cat docker-entrypoint.sh 
#!/bin/sh

# Make sure service is running
service rsyslog start

# Touch the log file so we can tail on it
touch /var/log/haproxy.log

# Throw the log to output
tail -f /var/log/haproxy.log &

# Start haproxy
exec haproxy -f /usr/local/etc/haproxy/haproxy.cfg
```

Can you help me figure out what's wrong with my setup. I'm totally hitting the wall to setup this.

**Comment by RafPe** [comment]
Can you also paste your haproxy config ? Error seems to be related to that piece

**Comment by hierony94** [comment]
@RafPe , seems like I found a solution.

I changed the `docker-entrypoint.sh`script to be like this

```
#!/bin/sh

set -e

#Make the log file & change log file permission
touch /var/log/haproxy/haproxy.log
chmod 644 /var/log/haproxy/haproxy.log

haproxy -f /usr/local/etc/haproxy/haproxy.cfg
/usr/sbin/rsyslogd -n -f /etc/rsyslog.conf
```

And it works like a charm.
