### ISSUE TITLE
doesnt seem to work

### ISSUE THREAD

**Issue by richardudovich** [RafPe/docker-haproxy-rsyslog#8]
haproxy_1  | rsyslogd: module 'imuxsock' already in this config, cannot be added  [v8.24.0 try http://www.rsyslog.com/e/2221 ]
haproxy_1  | rsyslogd: module 'imklog' already in this config, cannot be added  [v8.24.0 try http://www.rsyslog.com/e/2221 ]
haproxy_1  | rsyslogd: module 'imudp' already in this config, cannot be added  [v8.24.0 try http://www.rsyslog.com/e/2221 ]
haproxy_1  | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
haproxy_1  | rsyslogd: activation of module imklog failed [v8.24.0 try http://www.rsyslog.com/e/2145 ]

**Comment by RafPe** [comment]
@richardudovich got latest version pushed and spinned... works absolutely fine 4me 
```
> [INSERT] RafPe $ docker run --rm -v ${PWD}/config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg -p 9080:80 rafpe/docker-haproxy-rsyslog:latest
Starting enhanced syslogd: rsyslogd.
[WARNING] 142/092124 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:30]: 'log-format' overrides previous 'option httplog' in 'defaults' section.
May 23 09:21:24 localhost haproxy[1]: Proxy http-in started.
May 23 09:21:24 localhost haproxy[1]: Proxy will-be-back-soon started.
May 23 09:21:34 localhost haproxy[1]: {type:haproxy,timestamp:1558603294,http_status:503,http_request:GET / HTTP/1.1,remote_addr:172.17.0.1,bytes_read:212,upstream_addr:-,backend_name:will-be-back-soon,retries:0,bytes_uploaded:135,upstream_response_time:-1,upstream_connect_time:-1,session_duration:0,termination_state:SC}
```

**Comment by RafPe** [comment]
Can you please specify what are you trying to do ?

**Comment by RafPe** [comment]
Need clarification

**Comment by richardudovich** [comment]
Hi All, sorry for the delayed replay, but yes this is working for me now as well... not sure what happened there, possibly i was running a diff image :/ sorry for inconvenience
